name: Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  # For setup-rust
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: {}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          channel: stable
          bins: cargo-hack
      - name: Clippy
        run: cargo hack clippy --feature-powerset --workspace
      - name: Test
        run: cargo hack test --feature-powerset --workspace
      - name: Docs
        run: cargo doc --no-deps --workspace --all-features

  python:
    name: Python bindings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - run: uv python install
      - run: uv sync --all-extras
      - run: uv run pytest

  c:
    name: C bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          channel: stable
          bins: cbindgen
      - name: Run tests
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
          cd build && ctest
      - name: Create archive
        run: |
          git archive --prefix=zeek-websocket-rs/ HEAD > bindings/c/examples/zeek-websocket-rs.tar
      - name: Patch CMake setup
        run: |
          sed -i "s~GIT_REPOSITORY.*$~URL\ file://\${CMAKE_CURRENT_SOURCE_DIR}/zeek-websocket-rs.tar~" bindings/c/examples/CMakeLists.txt
      - name: Build examples
        uses: threeal/cmake-action@725d1314ccf9ea922805d7e3f9d9bcbca892b406
        with:
          source-dir: bindings/c/examples

  node:
    name: Node bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 20
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          channel: stable
      - name: Install dependencies
        run: |
          npm ci
      - name: Build bindings
        run: |
          npm run build:debug
      - name: Run tests
        run: |
          npm test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          channel: stable
          bins: cargo-hack
          components: clippy,rustfmt
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      - uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16

  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: instrumentation
